apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.api.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.name }}
    spec:
      containers:
      - name: {{ .Values.api.name }}
        image: "{{ .Values.api.deployment.image }}:{{ .Values.api.deployment.imageVersion }}"
        ports:
        - containerPort: {{ .Values.api.port }}
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.secret.name }}
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.secret.name }}
              key: password
        - name: POSTGRES_DB
          value: {{ .Values.db.dbName }}
        - name: dbhost
          value: "{{ .Values.db.name }}-service"
        - name: dbport
          value: "{{ .Values.db.port }}"