# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.lavinmq.name }}-service-management"
spec:
  selector:
    app: {{ .Values.lavinmq.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.lavinmq.managementPort }}
      targetPort: {{ .Values.lavinmq.managementPort }}
      name: "tcp-{{ .Values.lavinmq.managementPort }}"
      nodePort: {{ .Values.lavinmq.service.nodePort }}
  type: NodePort
