apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.lavinmq.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.lavinmq.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.lavinmq.name }}
    spec:
      containers:
      - name: {{ .Values.lavinmq.name }}
        image: "{{ .Values.lavinmq.deployment.image }}:{{ .Values.lavinmq.deployment.imageVersion }}"
        ports:
        - containerPort: {{ .Values.lavinmq.port }}
        - containerPort: {{ .Values.lavinmq.managementPort }}