# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.lavinmq.name }}-service"
spec:
  selector:
    app: {{ .Values.lavinmq.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.lavinmq.port }}
      targetPort: {{ .Values.lavinmq.port }}
      name: "tcp-{{ .Values.lavinmq.port }}"
  type: ClusterIP
