apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.db.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.name }}
    spec:
      volumes:
      - name: {{ .Values.db.configMap.name }}
        configMap:
          name: {{ .Values.db.configMap.name }}
      - name: {{ .Values.db.pvc.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.db.pvc.name }}
      containers:
      - name: {{ .Values.db.name }}
        image: "{{ .Values.db.deployment.image }}:{{ .Values.db.deployment.imageVersion }}"
        ports:
        - containerPort: {{ .Values.db.port }}
        volumeMounts:
        - name: {{ .Values.db.pvc.name }}
          mountPath: "/var/lib/postgresql"
        - name: {{ .Values.db.configMap.name }}
          mountPath: "/docker-entrypoint-initdb.d"
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.secret.name }}
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.secret.name }}
              key: password
        - name: POSTGRES_DB
          value: {{ .Values.db.dbName }}
    
      