api:
  name: api
  port: 8001
  deployment:
    image: pandects/chat-app-api
    imageVersion: 1.01

app:
  name: app
  port: 8005
  deployment:
    image: pandects/chat-app-app
    imageVersion: 1.01
  service:
    nodePort: 30005

chat:
  name: chat
  port: 8002
  deployment:
    image: pandects/chat-app-chat
    imageVersion: 1.01
  service:
    nodePort: 30002

consumer:
  name: consumer
  deployment:
    image: pandects/chat-app-consumer
    imageVersion: 1.01

lavinmq:
  name: lavinmq
  port: 5672
  managementPort: 15672
  deployment:
    image: cloudamqp/lavinmq
    imageVersion: latest
  service:
    nodePort: 30672

user:
  name: user
  port: 8080
  deployment:
    image: pandects/chat-app-user
    imageVersion: 1.01
  service:
    nodePort: 30080

db:
  name: postgres
  port: 5432
  dbName: chat-app
  configMap:
    name: init-scripts
  secret:
    name: sql-credentials
    username: guest
    password: guest
  deployment:
    image: library/postgres
    imageVersion: latest
  pvc:
    name: postgres-pvc
    size: 10Gi

pv:
  name: pv
  hostPath: "/tmp"
  size: 10Gi